L'eric no sap programar
royalmo/TripleBot pull request #3
Opened 2021-01-08 21:59 UTC by BinarySandia04

Eric t'he fet el codi millor, siusplau accepta'l no sé si funciona pero hauria de fer-ho

2021-01-08 22:02 UTC, BinarySandia04 commented
**BTW CAL ACLARAR UNA COSA**

La funció `def isInt(s)` no converteix les strings en int, només comprova si es pot transformar, la he liat a l'hora de fer el comentari, i crec que cal que ho tingui en compte ja que la conducta del codi diu que els comentaris han de ser clars, concissos i entenedors i per tant, cal destacar aquest petit error humà.

2021-01-09 11:37 UTC, royalmo requested changes
Doncs si has vist que falta convertir a int, fes el canvi en un commit (es posara automaticament dins la PR si ho fas a la mateixa branch)

2021-01-09 11:55 UTC, royalmo requested changes
Que passa si poso `!code JKDSFH -3`?

2021-01-09 11:55 UTC, royalmo commented on triplebot.py
> +                    code = code*timesInt
Crak fiera mastodonte has de multiplicar-ho com a mínim, pero aixo et pot petar igualment crak fiera titan furia.

Que passa si poso `!code JKDSFH -3`

2021-01-09 11:55 UTC, royalmo commented on triplebot.py
> +            laputaeric = content.split()
Hauries pogut agafar algo mes family friendly

2021-01-09 11:59 UTC, royalmo approved these changes
Ja t'ho he arreglat pq veig que et costa una miqueta xD anda en 10 mins ho tens al bot

2021-01-09 12:01 UTC, merged

2021-01-09 13:29 UTC, BinarySandia04 commented
Wow Eric no m esperaba q possessis un nombre negatiu per multiplicar un string, no m havia adonat compte d aquest cas (igualment t ho vaig fer a cegues pq ni el vaig executar xd)